dbconfig:
  oaMysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.8:2506/oa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    databaseName: oa
    username: root
    password: 123.abc.X
  oaSqlServer:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=OA20160401
    databaseName: OA20160401
    username: OA20151231
    password: hg123.XX
  mysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/enquiry_dev?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    databaseName: enquiry_dev
    username: root
    password: root
logging:
    level:
        com:
            example:
                demomybatis:
                    mapper: DEBUG
