dbconfig:
  oaMysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.8:2506/oa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    databaseName: oa
    username: root
    password: 123.abc.X
  oasqlserver:
        driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=OA20160401
        username: OA20151231
        password: hg123.XX
  mysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/enquiry_dev?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    databaseName: enquiry_dev
    username: root
    password: root
  oapg:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://192.168.2.8:21532/sixioa
      databaseName: sixioa
      username: testuser1
      password: 123456X

logging:
    level:
        com:
            example:
                demomybatis:
                    mapper: DEBUG

#Redis缓存配置
redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # 连接超时时间（毫秒）
  timeout: 6000
  # 连接池最大连接数（使用负值表示没有限制）
  max-active: 50
  # 连接池中的最大空闲连接
  max-idle: 50
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  max-wait: 3000
  # 连接池中的最小空闲连接
  min-idle: 10
spring:
  rabbitmq:
    host: 127.0.0.1
    username: cj
    password: cj123
    port: 5672
    virtual-host: /


#user:
# random:
#  secret: ${random.value}
#  intNumber: ${random.int}
#  longNumber: ${random.long}
#  uuid: ${random.uuid}
#  lessTen: ${random.int{10}}
#  range: ${random.int[1024,65536]}

